App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 20m
          maxSizeMessage: "Image size over 20M"

App\Request\ClientRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\ClientRegisterByDashboardRequest:
  properties:
    userID:
      - NotBlank: ~

App\Request\OrderShipmentCreateRequest:
  properties:
    clientUserID:
      - NotBlank: ~
    transportationType:
      - NotBlank: ~
    target:
      - NotBlank: ~
    quantity:
      - NotBlank: ~
    productCategoryID:
      - NotBlank: ~
    unit:
      - NotBlank: ~
    receiverID:
      - NotBlank: ~
    paymentTime:
      - NotBlank: ~
    holderType:
      - NotBlank: ~

App\Request\OrderShipmentByDashboardCreateRequest:
  properties:
    clientUserID:
      - NotBlank: ~
    transportationType:
      - NotBlank: ~
    target:
      - NotBlank: ~
    quantity:
      - NotBlank: ~
    productCategoryID:
      - NotBlank: ~
    unit:
      - NotBlank: ~
    receiverName:
      - NotBlank: ~
    receiverPhoneNumber:
      - NotBlank: ~
    paymentTime:
      - NotBlank: ~
    holderType:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\OrderShipmentByDashboardUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ShipmentOrderStatusUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\TrackCreateRequest:
  properties:
    shipmentID:
      - NotBlank: ~
    holderType:
      - NotBlank: ~
    holderID:
      - NotBlank: ~
    trackNumber:
      - NotBlank: ~
    shipmentStatus:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\TrackUpdateRequest:
  properties:
    holderID:
      - NotBlank: ~
    travelID:
      - NotBlank: ~
    trackNumber:
      - NotBlank: ~
    shipmentStatus:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\SubcontractCreateRequest:
  properties:
    fullName:
      - NotBlank: ~
    serviceID:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\SubcontractUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    fullName:
      - NotBlank: ~
    serviceID:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\TravelCreateRequest:
  properties:
    createdBy:
      - NotBlank: ~

App\Request\TravelStatusUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~
    status:
      - NotBlank: ~

App\Request\TravelUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~
    type:
      - NotBlank: ~
    launchCountry:
      - NotBlank: ~
    destinationCountry:
      - NotBlank: ~
    launchDate:
      - NotBlank: ~
    arrivalDate:
      - NotBlank: ~
    travelNumber:
      - NotBlank: ~
    shipperID:
      - NotBlank: ~

App\Request\WarehouseCreateRequest:
  properties:
    name:
      - NotBlank: ~
    countryID:
      - NotBlank: ~
    city:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\WarehouseUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    countryID:
      - NotBlank: ~
    city:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ContainerCreateRequest:
  properties:
    specificationID:
      - NotBlank: ~
    type:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\DistributorCreateRequest:
  properties:
    fullName:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\DistributorUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    fullName:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\MarkCreateRequest:
  properties:
    clientUserID:
      - NotBlank: ~
    markNumber:
      - NotBlank: ~

App\Request\MarkCreateByDashboardRequest:
  properties:
    clientUserID:
      - NotBlank: ~
    markNumber:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ProductCategoryCreateRequest:
  properties:
    name:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ProductCategoryUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ProxyCreateRequest:
  properties:
    fullName:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ProxyUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    fullName:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\SupplierCreateRequest:
  properties:
    fullName:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\SupplierUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    fullName:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\CountryCreateRequest:
  properties:
    name:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\AirwaybillCreateRequest:
  properties:
    specificationID:
      - NotBlank: ~
    type:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\AirwaybillUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    specificationID:
      - NotBlank: ~
    airwaybillNumber:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\AirwaybillStatusUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    status:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ContainerUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    specificationID:
      - NotBlank: ~
    containerNumber:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ContainerStatusUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    status:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\UnitCreateRequest:
  properties:
    name:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\UnitUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\ServiceCreateRequest:
  properties:
    name:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ServiceUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\SubProductCategoryCreateRequest:
  properties:
    name:
      - NotBlank: ~
    productCategoryID:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\SubProductCategoryUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    name:
      - NotBlank: ~
    productCategoryID:
      - NotBlank: ~
    hsCode:
      - NotBlank: ~
    updatedBy:
      - NotBlank: ~

App\Request\TrackUpdateByHolderTypeAndIdRequest:
  properties:
    holderType:
      - NotBlank: ~
    holderID:
      - NotBlank: ~
    shipmentStatus:
      - NotBlank: ~

App\Request\TrackUpdateByTravelIdRequest:
  properties:
    travelID:
      - NotBlank: ~
    shipmentStatus:
      - NotBlank: ~

App\Request\TravelFinanceCreateRequest:
  properties:
    travelID:
      - NotBlank: ~
    stageCost:
      - NotBlank: ~
    status:
      - NotBlank: ~
    currency:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\CheckHolderRequest:
  properties:
    shipmentID:
      - NotBlank: ~
    holderType:
      - NotBlank: ~
    holderID:
      - NotBlank: ~
    trackNumber:
      - NotBlank: ~

App\Request\WarehouseFinanceCreateRequest:
  properties:
    warehouseID:
      - NotBlank: ~
    cost:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ReceiverCreateRequest:
  properties:
    fullName:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    clientUserID:
      - NotBlank: ~

App\Request\ReceiverCreateByDashboardRequest:
  properties:
    fullName:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    clientUserID:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ShipmentFinanceCreateRequest:
  properties:
    shipmentID:
      - NotBlank: ~
    trackNumber:
      - NotBlank: ~
    stageCost:
      - NotBlank: ~
    currency:
      - NotBlank: ~
    shipmentStatus:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\AirwaybillFinanceCreateRequest:
  properties:
    airwaybillID:
      - NotBlank: ~
    stageCost:
      - NotBlank: ~
    currency:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ContainerFinanceCreateRequest:
  properties:
    containerID:
      - NotBlank: ~
    stageCost:
      - NotBlank: ~
    currency:
      - NotBlank: ~
    status:
      - NotBlank: ~
    createdBy:
      - NotBlank: ~

App\Request\ReceiverUpdateRequest:
  properties:
    id:
      - NotBlank: ~

App\Request\PendingHolderCreateRequest:
  properties:
    shipmentID:
      - NotBlank: ~
    specificationID:
      - NotBlank: ~
      