App\Request\UserRegisterRequest:
  properties:
    userID:
      - NotBlank: ~
    password:
      - NotBlank: ~

App\Request\UserProfileCreateRequest:
  properties:
    userName:
      - NotBlank: ~

App\Request\SupplierCreateRequest:
  properties:
    fullName:
      - NotBlank: ~

App\Request\SupplierUpdateRequest:
  properties:
    id:
      - NotBlank: ~
    fullName:
      - NotBlank: ~